name: BattleRoyale
version: '${project.version}'
main: me.edstorm17.battleroyale.BattleRoyale
api-version: '1.21'
commands:
  match:
    usage: /<command>
  items:
    usage: /<command>
  vehicle:
    usage: /<command>
  stuff:
    usage: /<command>

