name: BattleRoyale
version: '1.0-SNAPSHOT'
main: me.edstorm17.battleroyale.BattleRoyale
api-version: '1.21'
commands:
  battle:
    usage: /<command>
  items:
    usage: /<command>
  vehicle:
    usage: /<command>
  stuff:
    usage: /<command>
  i:
    usage: /<command>
  kit:
    usage: /<command>
